// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "interface.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



SendData_ptr SendData_Helper::_nil() {
  return ::SendData::_nil();
}

::CORBA::Boolean SendData_Helper::is_nil(::SendData_ptr p) {
  return ::CORBA::is_nil(p);

}

void SendData_Helper::release(::SendData_ptr p) {
  ::CORBA::release(p);
}

void SendData_Helper::marshalObjRef(::SendData_ptr obj, cdrStream& s) {
  ::SendData::_marshalObjRef(obj, s);
}

SendData_ptr SendData_Helper::unmarshalObjRef(cdrStream& s) {
  return ::SendData::_unmarshalObjRef(s);
}

void SendData_Helper::duplicate(::SendData_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

SendData_ptr
SendData::_duplicate(::SendData_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

SendData_ptr
SendData::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


SendData_ptr
SendData::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

SendData_ptr
SendData::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_SendData _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_SendData* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_SendData;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* SendData::_PD_repoId = "IDL:SendData:1.0";


_objref_SendData::~_objref_SendData() {
  
}


_objref_SendData::_objref_SendData(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::SendData::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_SendData::_ptrToObjRef(const char* id)
{
  if (id == ::SendData::_PD_repoId)
    return (::SendData_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::SendData::_PD_repoId))
    return (::SendData_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for SendData::putChar

// Proxy call descriptor class. Mangled signature:
//  void_i_cchar
class _0RL_cd_418088fd2cd063c6_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_418088fd2cd063c6_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::Char arg_0;
};

void _0RL_cd_418088fd2cd063c6_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalChar(arg_0);

}

void _0RL_cd_418088fd2cd063c6_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0 = _n.unmarshalChar();

}

const char* const _0RL_cd_418088fd2cd063c6_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_418088fd2cd063c6_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_418088fd2cd063c6_00000000* tcd = (_0RL_cd_418088fd2cd063c6_00000000*)cd;
  _impl_SendData* impl = (_impl_SendData*) svnt->_ptrToInterface(SendData::_PD_repoId);
  impl->putChar(tcd->arg_0);


}

void _objref_SendData::putChar(::CORBA::Char msg)
{
  _0RL_cd_418088fd2cd063c6_00000000 _call_desc(_0RL_lcfn_418088fd2cd063c6_10000000, "putChar", 8);
  _call_desc.arg_0 = msg;

  _invoke(_call_desc);



}

_pof_SendData::~_pof_SendData() {}


omniObjRef*
_pof_SendData::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_SendData(ior, id);
}


::CORBA::Boolean
_pof_SendData::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::SendData::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_SendData _the_pof_SendData;

_impl_SendData::~_impl_SendData() {}


::CORBA::Boolean
_impl_SendData::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "putChar")) {

    _0RL_cd_418088fd2cd063c6_00000000 _call_desc(_0RL_lcfn_418088fd2cd063c6_10000000, "putChar", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_SendData::_ptrToInterface(const char* id)
{
  if (id == ::SendData::_PD_repoId)
    return (::_impl_SendData*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::SendData::_PD_repoId))
    return (::_impl_SendData*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_SendData::_mostDerivedRepoId()
{
  return ::SendData::_PD_repoId;
}

POA_SendData::~POA_SendData() {}

