// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __interface_hh__
#define __interface_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_interface
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_interface
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_interface
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



#ifndef __SendData__
#define __SendData__
class SendData;
class _objref_SendData;
class _impl_SendData;

typedef _objref_SendData* SendData_ptr;
typedef SendData_ptr SendDataRef;

class SendData_Helper {
public:
  typedef SendData_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_SendData, SendData_Helper> SendData_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_SendData,SendData_Helper > SendData_out;

#endif

// interface SendData
class SendData {
public:
  // Declarations for this interface type.
  typedef SendData_ptr _ptr_type;
  typedef SendData_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_SendData :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  void putChar(::CORBA::Char msg);

  // Constructors
  inline _objref_SendData()  { _PR_setobj(0); }  // nil
  _objref_SendData(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_SendData();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_SendData(const _objref_SendData&);
  _objref_SendData& operator = (const _objref_SendData&);
  // not implemented

  friend class SendData;
};

class _pof_SendData : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_SendData() : _OMNI_NS(proxyObjectFactory)(SendData::_PD_repoId) {}
  virtual ~_pof_SendData();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_SendData :
  public virtual omniServant
{
public:
  virtual ~_impl_SendData();

  virtual void putChar(::CORBA::Char msg) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_SendData :
  public virtual _impl_SendData,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_SendData();

  inline ::SendData_ptr _this() {
    return (::SendData_ptr) _do_this(::SendData::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
SendData::_marshalObjRef(::SendData_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_interface
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_interface
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_interface
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_interface
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_interface
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_interface
#endif

#endif  // __interface_hh__

